#!/bin/bash

# ==============================================
# Air Hockey Smart Contract Deployment Script
# ==============================================
# This script builds and deploys the Air Hockey contract to Linera testnet
#
# Prerequisites:
# 1. Rust installed with wasm32-unknown-unknown target
# 2. Linera CLI installed (curl -L https://linera.io/install.sh | bash)
# 3. Internet connection to Linera testnet

set -e

echo "========================================"
echo "Air Hockey Contract Deployment"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
CONTRACT_DIR="$(dirname "$0")/air-hockey"
FAUCET_URL="https://faucet.testnet-archimedes.linera.net"

# Check prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! command -v rustc &> /dev/null; then
    echo -e "${RED}Error: Rust is not installed${NC}"
    echo "Install with: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi

if ! command -v linera &> /dev/null; then
    echo -e "${RED}Error: Linera CLI is not installed${NC}"
    echo "Install with: curl -L https://linera.io/install.sh | bash"
    exit 1
fi

# Check for wasm32 target
if ! rustup target list --installed | grep -q "wasm32-unknown-unknown"; then
    echo -e "${YELLOW}Installing wasm32-unknown-unknown target...${NC}"
    rustup target add wasm32-unknown-unknown
fi

echo -e "${GREEN}Prerequisites OK${NC}"

# Build the contract
echo -e "\n${YELLOW}Building contract...${NC}"
cd "$CONTRACT_DIR"

cargo build --release --target wasm32-unknown-unknown

if [ ! -f "target/wasm32-unknown-unknown/release/air_hockey_contract.wasm" ]; then
    echo -e "${RED}Error: Contract WASM not found after build${NC}"
    exit 1
fi

if [ ! -f "target/wasm32-unknown-unknown/release/air_hockey_service.wasm" ]; then
    echo -e "${RED}Error: Service WASM not found after build${NC}"
    exit 1
fi

echo -e "${GREEN}Contract built successfully${NC}"

# Initialize wallet if not exists
echo -e "\n${YELLOW}Setting up wallet...${NC}"

if [ ! -f ~/.linera/wallet.json ]; then
    echo "Creating new wallet via faucet..."
    linera wallet init --faucet "$FAUCET_URL"
fi

# Get wallet info
CHAIN_ID=$(linera wallet show 2>/dev/null | grep "Chain ID" | head -1 | awk '{print $NF}')
if [ -z "$CHAIN_ID" ]; then
    echo -e "${RED}Error: Could not get chain ID${NC}"
    exit 1
fi

echo -e "Chain ID: ${GREEN}$CHAIN_ID${NC}"

# Deploy the contract
echo -e "\n${YELLOW}Deploying contract to Linera testnet...${NC}"

DEPLOY_OUTPUT=$(linera publish-and-create \
    target/wasm32-unknown-unknown/release/air_hockey_contract.wasm \
    target/wasm32-unknown-unknown/release/air_hockey_service.wasm \
    --json-argument "{\"owner\": \"$CHAIN_ID\"}" \
    2>&1)

# Extract application ID from output
APP_ID=$(echo "$DEPLOY_OUTPUT" | grep -oE '[a-f0-9]{64,}' | head -1)

if [ -z "$APP_ID" ]; then
    echo -e "${RED}Error: Could not extract application ID${NC}"
    echo "Deploy output:"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

echo -e "${GREEN}Contract deployed successfully!${NC}"
echo ""
echo "========================================"
echo "Deployment Results"
echo "========================================"
echo -e "Application ID: ${GREEN}$APP_ID${NC}"
echo -e "Chain ID: ${GREEN}$CHAIN_ID${NC}"
echo ""
echo "========================================"
echo "Environment Variables"
echo "========================================"
echo ""
echo "Add these to your .env.local file:"
echo ""
echo "NEXT_PUBLIC_USE_MOCK_LINERA=false"
echo "NEXT_PUBLIC_LINERA_APPLICATION_ID=$APP_ID"
echo "NEXT_PUBLIC_LINERA_CHAIN_ID=$CHAIN_ID"
echo "NEXT_PUBLIC_LINERA_FAUCET_URL=$FAUCET_URL"
echo "NEXT_PUBLIC_LINERA_NODE_URL=https://rpc.testnet-archimedes.linera.net"
echo "NEXT_PUBLIC_LINERA_NETWORK=Linera Testnet"
echo ""

# Save to file for convenience
ENV_FILE="$(dirname "$0")/../.env.linera"
cat > "$ENV_FILE" << EOF
# Linera Blockchain Configuration
# Generated by deploy.sh on $(date)

NEXT_PUBLIC_USE_MOCK_LINERA=false
NEXT_PUBLIC_LINERA_APPLICATION_ID=$APP_ID
NEXT_PUBLIC_LINERA_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_LINERA_FAUCET_URL=$FAUCET_URL
NEXT_PUBLIC_LINERA_NODE_URL=https://rpc.testnet-archimedes.linera.net
NEXT_PUBLIC_LINERA_NETWORK=Linera Testnet
EOF

echo -e "Configuration saved to: ${GREEN}$ENV_FILE${NC}"
echo ""
echo "To use in production, copy these values to your Vercel environment variables."
